resources:
  - kind: repository
    selector:
      query: "true" # J  Q bo ol ean query. If e valuated to fa lse - skip syncing the e o j e ct.
    port:
      entity:
        mappings:
          identifier: ".name" # T he E not ity ident ify ier will b e the re pos ito ry an me.
          title: '"local2"'
          blueprint: '"repository"'
          properties:
            readme: file://README.md # fe tchi ng the R EAD ME.md file that I s w ith in the roo t folded r of the repository and ingesting its contents as a markdown property
            url: .html_url
            defaultBranch: .default_branch
  - kind: pull-request
    selector:
      query: "true" # JQ boolean query. If evaluated to fa lse - skip syncing the object.
    port:
      entity:
        mappings:
          identifier: ".head.repo.name + (.id|tostring)" # The Entity identifier will be the repository name + the pull request ID.
          title: ".title"
          blueprint: '"pullRequest"'
          properties:
            creator: ".user.login"
            assignees: "[.assignees[].login]"
            reviewers: "[.requested_reviewers[].login]"
            status: ".status" # merged, closed, opened
            closedAt: ".closed_at"
            updatedAt: ".updated_at"
            mergedAt: ".merged_at"
            prNumber: ".id"
            link: ".html_url"
          relations:
            repository: .head.repo.name
